// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYV-XFKUFRja5-vUWinGxb9lMlWuKVYMo',
    appId: '1:76603482118:web:4125550cd2b6cddbdd6387',
    messagingSenderId: '76603482118',
    projectId: 'incuevue-app',
    authDomain: 'incuevue-app.firebaseapp.com',
    storageBucket: 'incuevue-app.firebasestorage.app',
    measurementId: 'G-8PGRDK8230',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPrPmfCbJ_h7Gfqff03ThgRJ1z-ltcGnU',
    appId: '1:76603482118:android:47b7d7467ea5e9d9dd6387',
    messagingSenderId: '76603482118',
    projectId: 'incuevue-app',
    storageBucket: 'incuevue-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAii4Pg36c03DFOlgO2Y8sGKX5LnCU3VlE',
    appId: '1:76603482118:ios:9716c41563d5dd6add6387',
    messagingSenderId: '76603482118',
    projectId: 'incuevue-app',
    storageBucket: 'incuevue-app.firebasestorage.app',
    iosBundleId: 'com.example.incubvueApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAii4Pg36c03DFOlgO2Y8sGKX5LnCU3VlE',
    appId: '1:76603482118:ios:9716c41563d5dd6add6387',
    messagingSenderId: '76603482118',
    projectId: 'incuevue-app',
    storageBucket: 'incuevue-app.firebasestorage.app',
    iosBundleId: 'com.example.incubvueApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYV-XFKUFRja5-vUWinGxb9lMlWuKVYMo',
    appId: '1:76603482118:web:608033023c2324f9dd6387',
    messagingSenderId: '76603482118',
    projectId: 'incuevue-app',
    authDomain: 'incuevue-app.firebaseapp.com',
    storageBucket: 'incuevue-app.firebasestorage.app',
    measurementId: 'G-KNCLG17DXX',
  );
}
